/// Flutter icons Iconsapp
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Iconsapp
///      fonts:
///       - asset: fonts/Iconsapp.ttf
///
/// 
/// * Iconic, Copyright (C) 2012 by P.J. Onori
///         Author:    P.J. Onori
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://somerandomdude.com/work/iconic/
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class Iconsapp {
  Iconsapp._();

  static const _kFontFam = 'Iconsapp';
  static const String? _kFontPkg = null;

  static const IconData resize_vertical = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData resize_horizontal = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData right_and_left_arrows_with_vertical_line_in_the_middle_mi44oyyjxy2z = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vertical_alignment_ya204mf6yqye = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vertical_alignment_yu5lza7okstz = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData left_and_right_11wtecpnwuem = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData back = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData draftL = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData front = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData draftR = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData left = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData right = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData grip_lines_vertical = IconData(0xf7a5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
